# This is the .toml file passed to Locomotion.
# For information on the different settings available, and an example file,
# see the Locomotion README: https://github.com/leoncvlt/loconotion/blob/master/README.md

# This page should be the root of your website. It's important.
page = https://nipunbatra.notion.site/Home-eb41ce7777ef4d69ab63fbf4f22e1b51
